version: "2.3"

services:

  unprotected-server:
    image: approov/php:8.1.4
    build: ./
    networks:
      - default
    command: sh -c "composer install && php artisan serve --port 8002 --host 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/unprotected-server/hello:/home/developer/workspace

  approov-token-check:
    image: approov/php:8.1.4
    build: ./
    networks:
      - default
    command: sh -c "composer install && php artisan serve --port 8002 --host 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-check/hello:/home/developer/workspace

  approov-token-binding-check:
    image: approov/php:8.1.4
    build: ./
    networks:
      - default
    command: sh -c "composer install && php artisan serve --port 8002 --host 0.0.0.0"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-binding-check/hello:/home/developer/workspace

